Feat/remove relationship attribute
atlanhq/atlas-metastore pull request #2744
Opened 2024-01-10 13:29 UTC by aarshi0301

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-01-16 10:11 UTC, checkaayush approved these changes
Mostly LGTM. Left a minor clarification comment. Let's get 1 more approval before merge.

2024-01-16 10:19 UTC, n5nk requested changes
Please check 
- if we need to document the change , since we have priorities set for append and remove , the way API behaves. 
- Error handling during remove , if relationship is not present.
- Also please squash all the commits to one commit

2024-01-16 10:22 UTC, aarshi0301 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityGraphDiscoveryV2.java
> +                if (entity.hasRemoveRelationshipAttribute(attrName)) {
Yes, If both are true 
Then there are 2 cases:

   1. if assets in both appendRelationshipAttribute and removeRelationshipAttribute are different
      i. create relation for assets in appendRelationshipAttribute if not exits.
     ii.  remove relation for assets in removeRelationshipAttribute if exits.
    
    2. if assets in both appendRelationshipAttribute and removeRelationshipAttribute are same (ex asset A):
          i. create relation for assets in appendRelationshipAttribute if not exits. (relation with assetA gets created)
          ii. remove relation for assets in removeRelationshipAttribute if exits. (relation with assetA gets deleted now)

2024-01-17 14:25 UTC, aarshi0301 commented
> Please check
> 
> * if we need to document the change , since we have priorities set for append and remove , the way API behaves.
> * Error handling during remove , if relationship is not present.
> * Also please squash all the commits to one commit

Squashed commits

2024-01-17 14:27 UTC, aarshi0301 reviewed
Done

2024-01-17 14:59 UTC, n5nk approved these changes

2024-01-17 15:00 UTC, merged