Addition of restrictPropagationThroughHierarchy flag in classification propagation
atlanhq/atlas-metastore pull request #2891
Opened 2024-03-26 06:41 UTC by hr2904

## Change description
> Currently when a tag is propagated, it can be propagated to via a couple of paths
Via hierarchy
Via lineage

>When it comes to configure & customize these propagation paths, we only support restricting though lineage with restrictPropagationThroughLineage flag. This means propagations via hierarchy are not optional & done forcefully even when not required.

> To make it optional, we have introduced another flag which help to control propagations via hierarchy : `restrictPropagationThroughHierarchy`
> Added Argument of restrictThroughHierarchy in all methods where restrictThroughLineage was being passed, and handled the edge case of both flag being true. Added the concept of toExclude for : flag basis getting of labels.
> Handled all test cases and made fixes for them.
Added a method to test propagation config before sending it to Background task queue.

## Type of change
- [] New feature (adds functionality)

## Related issues

> Fix [#1](https://atlanhq.atlassian.net/browse/PLT-1036) 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-03-27 07:12 UTC, nikhilbonte21 requested changes

2024-03-27 10:08 UTC, nikhilbonte21 requested changes

2024-03-27 10:08 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
> +    public void createAndQueueTask(String taskType, AtlasVertex entityVertex, String classificationVertexId, String relationshipGuid, Boolean currentRestrictPropagationThroughLineage, Boolean current
This method is never called

2024-03-27 11:53 UTC, hr2904 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/ClassificationAssociator.java
> +            entityRetriever.verifyClassificationsPropagationMode(incomingClassifications);
I checked, EntityGraphRetirever is the only common place for this method to be put in.
Therefore calling it here

2024-03-29 09:31 UTC, checkaayush approved these changes
LGTM.

2024-04-01 13:32 UTC, nikhilbonte21 approved these changes

2024-04-02 04:31 UTC, merged