DG-1370 Write Mesh parent attributes in server
atlanhq/atlas-metastore pull request #3076
Opened 2024-05-13 18:35 UTC by hr2904

## Change description

> When a customer creates a relation between data domains or products, its done with qualifiedName, parentQualfiedName, and SuperDomainQualifiedName. These are variable string which can be abused by customer, and thus leading to inconsistency when traversing a hierarchy. Changed the relation logic from being qualifiedName to relationalAttribute. 
## Type of change
- [ ] Bug fix (fixes an issue)

## Related issues

> Fix [#1](https://atlanhq.atlassian.net/browse/DG-1370)

2024-05-16 21:22 UTC, nikhilbonte21 requested changes

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
> +            entity.setAttribute(QUALIFIED_NAME, createQualifiedName(parentDomainQualifiedName));
Move this line out if else, this should be called always

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataDomainPreProcessor.java
> +            }
Also we do not need additional if check here, move this logic to previous if if(parentDomainObject != null ){}

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
>          AtlasPerfMetrics.MetricRecorder metricRecorder = RequestContext.get().startMetricRecord("domainExists");
"domainExists" -> "productExists"

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
> +            processMoveDataProductToAnotherDomain(entity, currentParentDomainQualifiedName, newParentDomainQualifiedName, vertexQnName, newSuperDomainQualifiedName, storedProduct.getGuid());
No need to pass storedProduct.getGuid(), can be extracted from entity

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
> +            currentParentDomainQualifiedName = "";
why setting currentParentDomainQualifiedName to "" ?

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
> +            }
I think this is not needed

2024-05-16 21:22 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
> +            }
Products does not have relationship with name DATA_PRODUCT_REL_TYPE

2024-05-17 05:41 UTC, hr2904 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/AbstractDomainPreProcessor.java
> +        if(Objects.nonNull(guid) && StringUtils.isNotEmpty(guid)){
> StringUtils.isNotEmpty(guid) is enough as it takes care of null as well as empty

Have added a Objects.nonNull check as well, i feel wouldnt that be enough for null and empty string?

2024-05-17 16:01 UTC, nikhilbonte21 approved these changes

2024-05-22 06:01 UTC, mehtaanshul commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/datamesh/DataProductPreProcessor.java
> +            entity.removeAttribute(PARENT_DOMAIN_QN_ATTR);
throw error

2024-05-22 15:53 UTC, nikhilbonte21 approved these changes

2024-05-23 07:19 UTC, mehtaanshul approved these changes

2024-05-23 07:20 UTC, merged