DG-1432 Auth Policies for MQ related Items
atlanhq/atlas-metastore pull request #3243
Opened 2024-06-13 01:53 UTC by arpit-at

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-06-13 05:37 UTC, nikhilbonte21 requested changes

2024-06-13 05:37 UTC, nikhilbonte21 commented on addons/policies/bootstrap_entity_policies.json
> +                "policyCategory": "bootstrap",
Just for confirmation, are there any relationships defined between any of these new types, if yes i think we need to bootstrap relationship policies as well

2024-06-13 06:41 UTC, nikhilbonte21 approved these changes

2024-06-13 08:40 UTC, mehtaanshul commented on addons/policies/bootstrap_relationship_policies.json
> +                    "relationship-type:*"
specify relationship-type

2024-06-13 08:40 UTC, mehtaanshul commented on addons/policies/bootstrap_relationship_policies.json
> +                    "relationship-type:*"
specify relationship-type

2024-06-13 08:42 UTC, mehtaanshul commented on addons/policies/bootstrap_entity_policies.json
> +                    "entity-type:BusinessPolicyIncident",
Since BusinessPolicyIncident is subtype of Incident, we don't need specify it separately

2024-06-14 07:14 UTC, nikhilbonte21 approved these changes

2024-06-20 12:46 UTC, mehtaanshul approved these changes

2024-06-20 16:57 UTC, merged