DQ-295 Making type optional and auto-detecting by qName
atlanhq/atlas-metastore pull request #3305
Opened 2024-07-03 14:21 UTC by bichitra95

## Change description

> Description here

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-07-19 10:43 UTC, nikhilbonte21 requested changes

2024-07-19 10:43 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/contract/DataContract.java
> +                    throw new AtlasBaseException(String.format("type: %s value not supported yet.", s));
Send Error code

2024-07-19 10:43 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/contract/AbstractContractPreProcessor.java
> +                    "Please specify the `type` attribute in contract.");
Send BAD_REQUEST error code

2024-07-19 11:50 UTC, nikhilbonte21 approved these changes

2024-07-24 04:42 UTC, sumandas0 approved these changes

2024-07-24 04:59 UTC, merged