DG-1851 Fix : classificationEdge count causing statement overflow in CQL in Cassandra while running tag-cleanup-task
atlanhq/atlas-metastore pull request #3623
Opened 2024-10-10 12:29 UTC by hr2904

## Change description

> No pagination on number classificationEdges being get from asset vertex was causing 65535+ CQL statements to be commited at once into cassandra, which was failing the tag-cleanup-task. Added pagination for this.

# Screenshots
Before : 
![image](https://github.com/user-attachments/assets/fe56577d-8808-49af-8c2a-b5a6718edbe0)
After : 
Ran cleanup with 78999 classificationedges
![image](https://github.com/user-attachments/assets/1868ac65-6166-4d48-8a76-0b6ffc49966a)
![image](https://github.com/user-attachments/assets/3702b3c1-2bf6-4b93-a81e-f4b7dfb24ae5)
![image](https://github.com/user-attachments/assets/0419a656-be93-4c63-b3b7-2ca49fd51da0)
![image](https://github.com/user-attachments/assets/515f0e81-2fc8-4bd9-a531-b221ad624b5c)
Finally : 
![image](https://github.com/user-attachments/assets/2554d4ea-3f32-4922-a649-0814d53e3f44)
![image](https://github.com/user-attachments/assets/56fea781-05df-4596-b693-6e277f6826ad)

# TestCase : 150 edges 1 asset
<img width="624" alt="image" src="https://github.com/user-attachments/assets/5ed22126-8820-4f2e-9617-f2ba6bfb83a4">
<img width="417" alt="image" src="https://github.com/user-attachments/assets/bef6c672-a0a3-4184-9e42-3f55fab68206">

# TestCase : 75edges per asset. 2 asset thus 150 edges total
<img width="584" alt="image" src="https://github.com/user-attachments/assets/1acfdf81-6538-4953-9928-887ded06b4cc">
<img width="407" alt="image" src="https://github.com/user-attachments/assets/e977b3b3-f105-4e63-9771-c89eaac00fc6">

# Testcase : 150 edges 150 assets

<img width="393" alt="image" src="https://github.com/user-attachments/assets/4e25e11b-7e87-4b27-bf4a-24bb8224e2dc">
<img width="428" alt="image" src="https://github.com/user-attachments/assets/31b6cc67-3b07-49c9-b25b-05b97fba6f62">
<img width="440" alt="image" src="https://github.com/user-attachments/assets/ebbe3418-3728-4972-891f-c52ad2048ef6">
<img width="422" alt="image" src="https://github.com/user-attachments/assets/5925c63e-a5ad-485f-9e6e-869bbab7e8ff">

## Type of change
- [x] Bug fix (fixes an issue)

## Related issues

> Fix [#1](https://atlanhq.atlassian.net/browse/DG-1851) 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-10-10 13:15 UTC, nikhilbonte21 requested changes

2024-10-10 13:15 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
>                                  }
This for loop needs to be optimized
Only commit if edges size is 100
i.e. Imagine having 150 assets each having only single edge to this Tag, such a case will call transactionInterceptHelper.intercept(); 150 times where we only want to call it twice

2024-10-10 13:15 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
>                                  }
Also, mind sending notifications part where you need to call send notifications still 150 times in this case but only after interceptor call
So you can maintain a map which will hold all assets & classificationList removed in 100 batch & one commit is successful you iterate map to send 100 notifications

2024-10-10 13:15 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
>                                  }
Another scenario for notifications part would be single asset having more that 100 edges, surely edge deleting must be in 100 batch but notifications part should be only called at the end when you ensure all edges for the Asset are deleted

2024-10-15 05:12 UTC, nikhilbonte21 approved these changes

2024-10-15 05:55 UTC, sumandas0 approved these changes

2024-10-15 05:57 UTC, merged