DG-1869 Evaluates API cache optimisation.
atlanhq/atlas-metastore pull request #3819
Opened 2024-12-04 09:53 UTC by hr2904

## Change description

> In simple usecase of evaluates API from UI, multiple entities with same entityGuid or entityId were being fetched. for each entityGuid or entityId, we were fetching AtlasEntityHeader from DB, which was unnecessary as calls for same entityGuid or Id were redundant, thus added caching to optimise the flow.

## Type of change
- [ ] Bug fix (fixes an issue)

## Related issues

> Fix [Ticket](https://atlanhq.atlassian.net/browse/DG-1869) 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-12-09 13:38 UTC, nikhilbonte21 requested changes

2024-12-10 10:37 UTC, hr2904 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
> +                            end1Entity = atlasEntityHeaderCache.get(cacheKeyEnd1);
Got my answer to previous comment here. Thanks

2024-12-10 10:41 UTC, hr2904 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
> +        return (guid != null ? guid : "") + "|" + (id != null ? id : "") + "|" + (typeName != null ? typeName : "");
No, i have seen that at times guid is sent as null but entityId is sent i.e QN. If i will not store entityId, we will run into cache collision.
Along with that in a good memoisation all method-paramters are concatenated and return value from the method is stored as value.

2024-12-10 10:48 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
> +        return (guid != null ? guid : "") + "|" + (id != null ? id : "") + "|" + (typeName != null ? typeName : "");
Got it, it will help in scenarios where qualifiedName & typeName are passed as an entity reference.

2025-01-02 09:16 UTC, PRATHAM2002-DS approved these changes

2025-01-02 09:23 UTC, nikhilbonte21 approved these changes

2025-01-02 09:23 UTC, nikhilbonte21 commented on server-api/src/main/java/org/apache/atlas/RequestContext.java
> +
Getters & setters are not needed

2025-01-15 08:51 UTC, merged