Added task info in audit and kafka headers.
atlanhq/atlas-metastore pull request #3904
Opened 2024-12-23 06:17 UTC by hr2904

## Change description

> Adding header into the requestContext for task processing to add task-guid to the audit logs.

## Screenshots

<img width="823" alt="image" src="https://github.com/user-attachments/assets/20673220-8cc4-41ad-8f99-474b6c6a06b1" />
<img width="954" alt="image" src="https://github.com/user-attachments/assets/aa99866f-2b70-4984-a0de-ade142ab1098" />

## Type of change
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2025-01-02 11:05 UTC, krsoninikhil submitted a review, later dismissed
Discussion Slack thread https://atlanhq.slack.com/archives/C05NR8V0RE3/p1735806556621999

2025-01-20 05:46 UTC, nikhilbonte21 requested changes

2025-01-20 05:46 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/tasks/ClassificationTask.java
> +        RequestContext.get().addRequestContextHeader(X_ATLAN_TASK_GUID, getTaskGuid());
Move both lines to AbstractTask.java
This way it will be applicable to Meanings tasks as well & also for future further extensions of AbstractTask will be covered

2025-01-22 18:50 UTC, hr2904 commented on repository/src/main/java/org/apache/atlas/repository/store/graph/v2/tasks/ClassificationTask.java
> +        RequestContext.get().addRequestContextHeader(X_ATLAN_TASK_GUID, getTaskGuid());
fixed

2025-02-05 11:46 UTC, merged