MESH-299: Audit Search Logs
atlanhq/atlas-metastore pull request #3928
Opened 2024-12-30 13:19 UTC by ankitpatnaik-atlan

## Change description

> Enhanced audit logs to include changes in the attributes as per [issue](https://atlanhq.atlassian.net/browse/MESH-319).

## Type of change
- [ ] Bug fix (fixes an issue)
- [ x] New feature (adds functionality)

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

<img width="1440" alt="Screenshot 2024-12-30 at 6 45 07 PM" src="https://github.com/user-attachments/assets/c18af76b-36bb-4d7d-bae1-462a43fb0bd8" />
<img width="1440" alt="Screenshot 2024-12-30 at 5 09 51 PM" src="https://github.com/user-attachments/assets/3e22f3e8-d3d2-43ac-ab40-06e5ef18d71a" />

2024-12-31 08:12 UTC, PRATHAM2002-DS commented on repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
> +    private static final Set<String> guidKeys = new HashSet<>(Arrays.asList(DOMAIN_GUIDS));
Change variable name to linkedAttributes or something relevant

2024-12-31 08:12 UTC, PRATHAM2002-DS commented on intg/src/main/java/org/apache/atlas/model/audit/EntityAuditEventV2.java
> +        }
Why this function, are you using this anywhere

2024-12-31 08:12 UTC, PRATHAM2002-DS commented on repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
> +                    if (guidKeys.contains(entry.getKey()) && entry.getValue() instanceof List) {
entry.getValue() instanceof List , dont see need of this check now

2024-12-31 08:14 UTC, PRATHAM2002-DS commented on intg/src/main/java/org/apache/atlas/model/audit/EntityAuditEventV2.java
> +        }
Oh got the use here

2024-12-31 08:19 UTC, PRATHAM2002-DS commented on repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
> +                        if (!guids.isEmpty()){
Add a null check here

2025-01-02 07:44 UTC, PRATHAM2002-DS submitted a review, later dismissed

2025-01-02 11:13 UTC, krsoninikhil commented on repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
> +    }
Nit pick - is this extra method helping? If there is only a single line, it is extra hop for code reader to follow.

2025-01-02 11:37 UTC, ankitpatnaik-atlan commented on repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
> +
@krsoninikhil, would you like me to remove the fetchAtlasEntityHeader function and try to include the changes where the function call is happening?

2025-01-13 06:22 UTC, PRATHAM2002-DS approved these changes

2025-01-13 06:22 UTC, PRATHAM2002-DS commented on intg/src/main/java/org/apache/atlas/model/audit/EntityAuditEventV2.java
> +
Why this extra space, please remove if not intended

2025-01-13 07:49 UTC, ankitpatnaik-atlan commented on intg/src/main/java/org/apache/atlas/model/audit/EntityAuditEventV2.java
> +
extra spaces removed.

2025-01-14 07:28 UTC, nikhilbonte21 requested changes

2025-01-14 07:28 UTC, nikhilbonte21 commented on repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
> +                                    } catch (AtlasBaseException e) {
Since you have cached this exception here, let us add LOG.error explaining exception caught at extracting linked entities for events with a specific `eventKey` printed in error message

2025-01-14 09:13 UTC, nikhilbonte21 approved these changes

2025-01-14 12:51 UTC, merged